from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Numeric, Float
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from app.config.database import Base


class LabTestCatalog(Base):
    """The master dictionary of available laboratory tests."""
    __tablename__ = "lab_test_catalog"

    catalog_id = Column(Integer, primary_key=True)
    test_name = Column(String(255), unique=True, index=True, nullable=False)
    description = Column(String, nullable=True)
    category = Column(String(100), nullable=False)
    default_specimen_type = Column(String(100), nullable=False)

    base_price = Column(Numeric(10, 2), nullable=False)
    turnaround_hours = Column(Integer, default=24)
    is_active = Column(Boolean, default=True)

    # When False, the lab UI does not insist on barcode generation /
    # "Pending Collection" → "In Progress" transition. Defaults to False so
    # operators can resolve tests in a single click for low-volume or POC
    # workflows.
    requires_barcode = Column(Boolean, default=False, nullable=False)

    parameters = relationship(
        "LabCatalogParameter",
        back_populates="catalog",
        cascade="all, delete-orphan",
        order_by="LabCatalogParameter.sort_order",
    )


class LabCatalogParameter(Base):
    """Defines the discrete result fields a given lab test produces.

    Each catalog test can have an arbitrary number of parameters (Hemoglobin,
    WBC, Platelets, etc.) with units, reference ranges, and a value type. The
    lab UI renders the result-entry form straight from this table so adding
    a new test does NOT require a code change.
    """
    __tablename__ = "lab_catalog_parameters"

    parameter_id = Column(Integer, primary_key=True)
    catalog_id = Column(
        Integer,
        ForeignKey("lab_test_catalog.catalog_id", ondelete="CASCADE"),
        index=True,
        nullable=False,
    )
    key = Column(String(60), nullable=False)            # machine key, e.g. "wbc"
    name = Column(String(200), nullable=False)          # human label, e.g. "White Blood Cells"
    unit = Column(String(40), nullable=True)            # "x10⁹/L", "g/dL", etc.
    value_type = Column(String(20), default="number")   # number | text | choice
    choices = Column(String, nullable=True)             # comma-separated options when value_type=choice
    ref_low = Column(Float, nullable=True)
    ref_high = Column(Float, nullable=True)
    sort_order = Column(Integer, default=0)
    is_active = Column(Boolean, default=True)

    catalog = relationship("LabTestCatalog", back_populates="parameters")


class LabTestRequiredItem(Base):
    """The Bill of Materials (BOM) for a test. What reagents/consumables does it use?"""
    __tablename__ = "lab_test_required_items"

    id = Column(Integer, primary_key=True)
    catalog_id = Column(
        Integer,
        ForeignKey("lab_test_catalog.catalog_id", ondelete="CASCADE"),
        index=True,
    )
    inventory_item_id = Column(Integer, ForeignKey("inventory_items.item_id"), index=True)

    item_name = Column(String(255), nullable=False)
    quantity_required = Column(Integer, nullable=False)


class LabTest(Base):
    """The actual clinical order generated by a Doctor for a Patient."""
    __tablename__ = "lab_tests"

    test_id = Column(Integer, primary_key=True)

    # Traceability
    patient_id = Column(Integer, ForeignKey("patients.patient_id"), index=True, nullable=False)
    record_id = Column(Integer, ForeignKey("medical_records.record_id"), index=True, nullable=True)
    ordered_by = Column(Integer, ForeignKey("users.user_id"), index=True, nullable=False)
    catalog_id = Column(Integer, ForeignKey("lab_test_catalog.catalog_id"), index=True, nullable=False)

    # Order Details
    test_name = Column(String(255), nullable=False)
    clinical_notes = Column(String, nullable=True)
    billed_price = Column(Numeric(10, 2), nullable=False)

    # Specimen & Execution Tracking — barcode is OPTIONAL. Many low-throughput
    # workflows skip specimen labelling entirely; the field stays nullable so
    # those orders still flow through without forcing the UI to generate a
    # placeholder label.
    specimen_id = Column(String(100), unique=True, index=True, nullable=True)
    specimen_type = Column(String(100), nullable=True)
    status = Column(String(50), default="Pending", index=True)
    priority = Column(String(50), default="Routine", index=True)

    # Results
    result_summary = Column(String, nullable=True)
    result_data = Column(JSONB, nullable=True)
    lab_technician_notes = Column(String, nullable=True)

    # Timestamps
    requested_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    sample_collected_at = Column(DateTime(timezone=True), nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)
    performed_by_id = Column(Integer, ForeignKey("users.user_id"), index=True, nullable=True)
