from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Numeric
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from app.config.database import Base

class LabTestCatalog(Base):
    """The Master Dictionary of available Laboratory Tests."""
    __tablename__ = "lab_test_catalog"
    
    catalog_id = Column(Integer, primary_key=True)
    test_name = Column(String(255), unique=True, index=True, nullable=False)
    description = Column(String, nullable=True)
    category = Column(String(100), nullable=False) # e.g., Hematology, Biochemistry
    default_specimen_type = Column(String(100), nullable=False) # e.g., Blood, Urine, Swab
    
    base_price = Column(Numeric(10, 2), nullable=False)
    turnaround_hours = Column(Integer, default=24)
    is_active = Column(Boolean, default=True)

class LabTestRequiredItem(Base):
    """The Bill of Materials (BOM) for a test. What reagents/consumables does it use?"""
    __tablename__ = "lab_test_required_items"
    
    id = Column(Integer, primary_key=True)
    catalog_id = Column(Integer, ForeignKey("lab_test_catalog.catalog_id", ondelete="CASCADE"), index=True)
    inventory_item_id = Column(Integer, ForeignKey("inventory_items.item_id"), index=True) # Links to Master Inventory
    
    item_name = Column(String(255), nullable=False)
    quantity_required = Column(Integer, nullable=False) # How much to deduct from Lab Stock upon completion

class LabTest(Base):
    """The actual clinical order generated by a Doctor for a Patient."""
    __tablename__ = "lab_tests"
    
    test_id = Column(Integer, primary_key=True)
    
    # Traceability
    patient_id = Column(Integer, ForeignKey("patients.patient_id"), index=True, nullable=False)
    record_id = Column(Integer, ForeignKey("medical_records.record_id"), index=True, nullable=True) # The consultation that triggered this
    ordered_by = Column(Integer, ForeignKey("users.user_id"), index=True, nullable=False)
    catalog_id = Column(Integer, ForeignKey("lab_test_catalog.catalog_id"), index=True, nullable=False)
    
    # Order Details
    test_name = Column(String(255), nullable=False)
    clinical_notes = Column(String, nullable=True) # e.g., "Check for malaria parasites"
    billed_price = Column(Numeric(10, 2), nullable=False) # Locked in at order time to prevent pricing disputes
    
    # Specimen & Execution Tracking
    specimen_id = Column(String(100), unique=True, index=True, nullable=True) # Barcode generation
    specimen_type = Column(String(100), nullable=True)
    status = Column(String(50), default="Pending", index=True) # Pending / Sample Collected / In Progress / Completed / Cancelled
    priority = Column(String(50), default="Routine", index=True) # Routine, STAT, Urgent
    # Results
    result_summary = Column(String, nullable=True) # A quick text summary for the doctor's dashboard
    result_data = Column(JSONB, nullable=True) # Structured JSON for complex panels (e.g., {"WBC": 4.5, "RBC": 5.1})
    lab_technician_notes = Column(String, nullable=True)
    
    # Timestamps
    requested_at = Column(DateTime(timezone=True), server_default=func.now(), index=True)
    sample_collected_at = Column(DateTime(timezone=True), nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)
    performed_by_id = Column(Integer, ForeignKey("users.user_id"), index=True, nullable=True)