/**
 * Module journey step definitions.
 *
 * Each key maps to an array of steps. A step is:
 *   {
 *     selector?:  string,          // CSS selector to spotlight
 *     title:      string,
 *     body:       string,
 *     placement?: 'top' | 'bottom' | 'left' | 'right' | 'center',
 *     tip?:       string,          // optional brand-tinted callout shown
 *                                  // beneath the body — use for power-user
 *                                  // shortcuts or "did you know" notes
 *   }
 *
 * If `selector` doesn't resolve at runtime we silently fall back to a
 * centred card — so a tour never breaks when a target moves; it just
 * loses its arrow.
 *
 * Authoring philosophy: every step talks about what the USER does next,
 * not what the widget IS. A new staff member should be able to follow
 * these tours and run their full shift without training — orient, then
 * walk them through the actual workflow, button by button.
 */
export const JOURNEYS = {

    /* ──────────────────────────────────────────────────────────────
       Dashboard / Home — orient a fresh user to the shell
       ────────────────────────────────────────────────────────────── */
    dashboard: [
        { title: 'Welcome — let me show you how the shift runs',
          body: "Across every module the layout is the same: sidebar on the left for navigation, top bar for context and alerts, work area in the middle. Once you know where these live you can run the whole hospital from here without anyone training you.",
          placement: 'center' },
        { selector: '[data-tour="sidebar-nav"]',
          title: 'Step 1 — pick what you want to do',
          body: "The sidebar is your menu. Receptionists usually start with Patient Registry, doctors with Clinical Desk, pharmacists with Pharmacy. Tap any module to jump straight to it.",
          placement: 'right',
          tip: 'Anything your role isn\'t allowed to use is hidden — if you can see a link, you can use it.' },
        { selector: '[data-tour="topbar-help"]',
          title: 'Step 2 — if you ever feel lost, click "?"',
          body: "This help icon replays the walk-through for whatever page you're on. Hit it any time you forget where a button is — no need to ask a colleague or look up a manual.",
          placement: 'bottom' },
        { selector: '[data-tour="topbar-notifications"]',
          title: 'Step 3 — keep an eye on the bell',
          body: "Critical lab results, prescriptions waiting to be dispensed, appointments arriving — the bell flashes when something needs your attention. Click it to see the queue.",
          placement: 'bottom' },
        { selector: '[data-tour="active-patient-bar"]',
          title: 'Step 4 — your "patient in front of you"',
          body: "Whichever patient you've opened anywhere in the system stays pinned to this bar. Walk from Reception to Clinical to Pharmacy — every page already knows who you mean.",
          placement: 'bottom',
          tip: 'Click the bar to clear the active patient when you\'re done with them.' },
        { selector: '[data-tour="topbar-signout"]',
          title: 'Step 5 — sign out when you leave the workstation',
          body: "Sessions stay open until you sign out, so on a shared computer always click here when your shift ends. The next person signs in fresh under their own name.",
          placement: 'bottom' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Admin Dashboard — the Admin's first-day walkthrough
       ────────────────────────────────────────────────────────────── */
    admin: [
        { title: 'Command Center walk-through — run your hospital from one screen',
          body: "This is the Admin cockpit. We'll go through the order you follow on day one: read the dashboard, add staff, assign roles, set what you charge, and confirm every change is tracked.",
          placement: 'center' },
        { selector: '[data-tour="admin-tabs"]',
          title: 'Step 1 — your six tools',
          body: "Overview (live metrics), Directory (staff accounts), Departments, Roles (who can do what), Pricing (what you charge), and Audit (who did what). Click between them here — we'll start on Overview.",
          placement: 'bottom' },
        { selector: '[data-tour="admin-overview"]',
          title: 'Step 2 — read the cockpit',
          body: "Registered patients, today's billed revenue, active inpatient admissions, and low-stock alerts — the four numbers that tell you how the hospital is running right now.",
          placement: 'bottom' },
        { selector: '[data-tour="admin-provision"]',
          title: 'Step 3 — add your staff',
          body: "Open the Directory tab and click \"Provision New Account\". Enter their name, email, a temporary password, and pick a role. They can sign in and start working immediately. Lock the account of anyone who leaves to cut their access instantly.",
          placement: 'left',
          tip: 'Every staff change is written to the Audit ledger with your user ID and a timestamp — proof of who changed what.' },
        { selector: '[data-tour="admin-perms"]',
          title: 'Step 4 — fine-tune one person\'s access',
          body: "On any staff row, \"Edit Role\" swaps their whole role; \"Permissions\" grants or revokes individual permissions without building a new role — perfect for the one nurse who's also allowed to take cash. \"Lock/Unlock\" controls whether they can sign in at all.",
          placement: 'left' },
        { selector: '[data-tour="admin-tabs"]',
          title: 'Step 5 — roles, pricing & audit',
          body: "The remaining tabs: Roles lets you build custom roles (e.g. \"Senior Nurse\") and pick exactly what they can do; Pricing sets the fees the Billing module charges; Audit is the immutable log of every create/update/delete across the hospital. Click each to explore.",
          placement: 'bottom' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Patient Registry — Receptionist's full registration flow
       ────────────────────────────────────────────────────────────── */
    patients: [
        { title: 'Receptionist walk-through — register and route a patient',
          body: "This is where every patient starts their visit. We'll go through the exact sequence you'll do every day: check if they're already registered, register them if not, then route them to whichever department they need.",
          placement: 'center' },
        { selector: '[data-tour="patients-stats"]',
          title: 'Step 1 — glance at the strip when you arrive',
          body: 'Before opening the directory: how many active patients, how many registered today, how many flagged for allergies. Useful when a manager asks "how busy are we?" — you answer without leaving this screen.',
          placement: 'bottom' },
        { selector: '[data-tour="patient-search"]',
          title: 'Step 2 — search first, register second',
          body: "When a patient arrives, type their phone, ID, or surname here. If they come up — open them. If they don't — only then register them. This stops you from creating duplicates.",
          placement: 'bottom',
          tip: 'You can paste an OP number directly — even a partial one matches.' },
        { selector: '[data-tour="patients-filter-chips"]',
          title: 'Step 3 — narrow by sex if needed',
          body: 'If a patient\'s name is common, filter by Male or Female to shorten the list. Click "All" to clear.',
          placement: 'bottom' },
        { selector: '[data-tour="register-patient"]',
          title: 'Step 4 — register a new walk-in',
          body: 'No match in search? Click "Register patient". Fill in name, sex, date of birth, contact, next-of-kin, blood group, allergies. The form scrolls — finish every section.',
          placement: 'left',
          tip: 'The "Treatment consent" checkbox at the bottom is REQUIRED — without it the doctor cannot save any clinical notes for this patient later.' },
        { selector: '[data-tour="patient-row-route-chips"]',
          title: 'Step 5 — send them where they\'re going',
          body: "Once registered (or found), use these chips to put the patient into the right queue: Clinical (to see a doctor), Lab (for tests), Radiology (for imaging), Pharmacy (for refills), Wards (admission), or Billing (cashier).",
          placement: 'left',
          tip: 'A picker opens so you choose which doctor / pharmacist / nurse — that staff member sees the patient in their queue immediately.' },
        { selector: '[data-tour="patient-row-more"]',
          title: 'Step 6 — for anything else, open the ⋮ menu',
          body: "Edit patient details, view full medical history, print a patient card with their OP number, deactivate the file, or run a KDPA Section 26 access report — all under the three-dots menu.",
          placement: 'left' },
        { title: 'You\'re done',
          body: 'That\'s the receptionist\'s whole flow. Search → register if new → route. Repeat all day. Click "?" in the top bar if you ever want this walk-through again.',
          placement: 'center' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Clinical Desk — the Doctor's full consultation workflow
       ────────────────────────────────────────────────────────────── */
    clinical: [
        { title: 'Doctor walk-through — run a consultation end-to-end',
          body: "We'll walk through one full encounter the way you'll do every patient: pick them from your queue, record consent, fill vitals + SOAP, decide the diagnosis, then route them to Pharmacy / Billing / Wards. By the end you'll have the muscle memory for the whole shift.",
          placement: 'center' },
        { selector: '[data-tour="clinical-queue"]',
          title: 'Step 1 — pick the next patient',
          body: "Your queue lives at the top of the page. Reception routes patients to you and they appear here in order. Click any card to open their workspace.",
          placement: 'bottom',
          tip: 'Critical-priority patients show a pulsing red dot — see them first.' },
        { selector: '[data-tour="clinical-consent"]',
          title: 'Step 2 — record consent BEFORE you chart',
          body: 'Click "Record consent" right after opening the patient. Pick Verbal if they agreed face-to-face, Written if you have a signed form, Implied (Emergency) only if they can\'t communicate. Without active consent the system blocks every clinical save (KDPA Section 30).',
          placement: 'bottom',
          tip: 'Reception captures consent at registration, so most encounters won\'t need this step — but if you get a "no active consent" error, this is the fix.' },
        { selector: '[data-tour="clinical-vitals"]',
          title: 'Step 3 — fill vitals',
          body: "Blood pressure, heart rate, respiratory rate, temperature, SpO₂. Enter weight + height and BMI computes automatically. You can skip a field if it wasn't measured — none of these are forced.",
          placement: 'top' },
        { selector: '[data-tour="clinical-diagnoses"]',
          title: 'Step 4 — chief complaint, history, examination, diagnosis',
          body: 'Type the patient\'s chief complaint (one line — "headache for 3 days"), then the history of present illness (the story), then your physical examination findings. Pick or type an ICD-10 code for the diagnosis.',
          placement: 'top',
          tip: 'The ICD-10 dropdown filters as you type — start with a body system ("resp", "card") to narrow it.' },
        { selector: '[data-tour="clinical-prescriptions"]',
          title: 'Step 5 — write the prescription',
          body: 'This box is what Pharmacy sees. Write what the patient should take, in plain language ("Amoxicillin 500mg TDS for 5 days"). Pharmacy picks the actual batches.',
          placement: 'top',
          tip: 'Leave this blank if there\'s no prescription — but then don\'t use "Forward to pharmacy" below.' },
        { selector: '[data-tour="clinical-save-draft"]',
          title: 'Step 6a — "Save draft" if you\'re interrupted',
          body: 'Patient stepped out for an X-ray? Got pulled into an emergency? Click Save draft. The encounter stays in your workspace, the patient stays in your queue marked "In Consultation", and you pick up exactly where you left off.',
          placement: 'top' },
        { selector: '[data-tour="clinical-send-billing"]',
          title: 'Step 6b — "Send to billing" when consultation is done',
          body: "Use this when the patient only needs to pay the consultation fee and leave (no meds, no admission). The cashier sees them in the Billing queue with a pending invoice. The consultation fee posts automatically — leave the fee checkbox ON unless the patient is exempt.",
          placement: 'top',
          tip: 'You\'ll get a friendly error if you uncheck the fee AND haven\'t added any other charges — otherwise the cashier wouldn\'t know to call the patient.' },
        { selector: '[data-tour="clinical-forward-pharmacy"]',
          title: 'Step 6c — "Forward to pharmacy" for prescriptions',
          body: "Patient leaves the room and walks to Pharmacy with a prescription. The pharmacist sees them in their queue with your prescription text waiting. Requires the Medications field filled — otherwise the button refuses.",
          placement: 'top' },
        { selector: '[data-tour="clinical-finalize"]',
          title: 'Step 6d — "Finalise & sign" to close the encounter',
          body: "Use this when the encounter is fully done — no meds, no billing, no follow-up. The record locks, the queue clears, your workspace resets. Requires at least a chief complaint or a diagnosis (no blank sign-offs allowed).",
          placement: 'top' },
        { title: 'That\'s every consultation',
          body: 'Pick from queue → consent → vitals → SOAP → diagnosis → prescription → route. Repeat. The "?" icon in the top bar replays this any time you want.',
          placement: 'center' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Triage — the Nurse's vitals-and-acuity station
       ────────────────────────────────────────────────────────────── */
    triage: [
        { title: 'Triage walk-through — prep the patient for the doctor',
          body: "Triage is where you catch the patient before the consultation: take vitals, note why they came, and set how urgent they are. When you save, the doctor's desk opens pre-filled — they don't repeat your work.",
          placement: 'center' },
        { selector: '[data-tour="triage-queue"]',
          title: 'Step 1 — pick the next patient',
          body: "Reception routes patients here for triage and they appear in \"Awaiting Triage\". A red dot flags known allergies. Click a card to open the triage station for that patient.",
          placement: 'bottom' },
        { selector: '[data-tour="triage-vitals"]',
          title: 'Step 2 — record vitals',
          body: "BP, heart rate, respiratory rate, temperature, SpO₂, weight, height, pain score, and blood glucose. Enter weight + height and BMI computes automatically. Skip any field that wasn't measured — none are forced.",
          placement: 'top' },
        { selector: '[data-tour="triage-complaint"]',
          title: 'Step 3 — chief complaint & notes',
          body: "Write what brought the patient in today, plus any triage notes the doctor should see — mobility, how they look, anything off. This is the first thing the doctor reads.",
          placement: 'top' },
        { selector: '[data-tour="triage-acuity"]',
          title: 'Step 4 — set the acuity',
          body: "Pick how urgent they are, 1 (Emergency / resuscitation) to 5 (Non-urgent). This is what sorts the doctor's queue — acuity 1 jumps the line, so be honest with it.",
          placement: 'top',
          tip: 'If reception already set an acuity, it pre-selects here — bump it up or down based on what you find.' },
        { selector: '[data-tour="triage-save"]',
          title: 'Step 5 — save & send to the doctor',
          body: "Click \"Save & send to doctor\". The patient drops into the doctor's Consultation queue with everything you captured already filled in. You need at least one vital or the chief complaint — no empty hand-offs.",
          placement: 'top' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Medical History — Doctor / Nurse longitudinal chart
       ────────────────────────────────────────────────────────────── */
    medical_history: [
        { title: 'Walk-through — read and update a patient\'s long-term chart',
          body: "Clinical Desk is for what’s happening today. Medical History is for everything that has ever happened: surgeries, allergies, chronic conditions, immunisations, social context. We’ll walk through how to find a chart and add to it.",
          placement: 'center' },
        { selector: '[data-tour="mh-search"]',
          title: 'Step 1 — open a patient',
          body: "Type a name or OP number. The chart loads with every section pre-expanded so you can scan the whole timeline in one scroll.",
          placement: 'bottom' },
        { selector: '[data-tour="consent-card"]',
          title: 'Step 2 — verify consent first',
          body: 'Green banner = active Treatment consent, you can chart freely. Red banner = no active consent, every save will be blocked. If red, click "+ Record consent" right there to fix it.',
          placement: 'right',
          tip: 'Recording consent here is the same form as in Clinical Desk — same data lands in the same place.' },
        { selector: '[data-tour="mh-entry-section"]',
          title: 'Step 3 — scan the relevant section',
          body: "Each section (Surgical, Family, Social, Immunisations, Allergies, etc.) shows how many entries it has on its tag. Collapse sections you don't care about.",
          placement: 'top' },
        { selector: '[data-tour="mh-add-entry"]',
          title: 'Step 4 — add a new entry',
          body: "Click + on any section. Title, description, optional event date, severity, status (Active / Resolved / Managed / Remission). Saves into the timeline so the next clinician sees it.",
          placement: 'left' },
        { selector: '[data-tour="mh-print"]',
          title: 'Step 5 — print for a referral',
          body: "Sending the patient to a specialist outside the system? Print the summary. Includes the consent log so the receiving clinician can see scope.",
          placement: 'left' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Laboratory — Lab Technician's order-to-result flow
       ────────────────────────────────────────────────────────────── */
    laboratory: [
        { title: 'Lab technician walk-through — order to released result',
          body: "We'll run one test the way you'll do every sample: pick it off the queue, receive the specimen, enter the results, log the reagents you used, and release. Then the setup side — building your test menu.",
          placement: 'center' },
        { selector: '[data-tour="lab-tabs"]',
          title: 'Step 1 — the two sides of the lab',
          body: "\"Lab Operations\" is your bench: processing orders and entering results. \"Test Catalog\" is the setup side: defining the tests you offer and their parameters. Start in Lab Operations.",
          placement: 'bottom' },
        { selector: '[data-tour="lab-queue"]',
          title: 'Step 2 — see what doctors ordered',
          body: "Every lab request lands here with its status. STAT tests are flagged red — do those first. Each card shows the test, the patient, and when it was ordered. Click one to open it on the bench.",
          placement: 'bottom' },
        { selector: '[data-tour="lab-workbench"]',
          title: 'Step 3 — receive, run, and release',
          body: "The bench walks you through the lifecycle: if the test needs a barcode you'll \"Print barcode & receive\" the specimen first, then enter results into the form (built from that test's parameters — out-of-range values flag Low/High automatically), log any reagents used, and finally \"Verify, release & reconcile stock\". You can also reject a bad sample with a reason.",
          placement: 'top',
          tip: 'Reusable items (slides, probes) are logged on use without decrementing stock; consumable reagents deduct from the lab store.' },
        { selector: '[data-tour="lab-new-test"]',
          title: 'Setup — add a test to your menu',
          body: "Switch to the Test Catalog tab and click \"New test\". Set its name, category, specimen type, base price, and turnaround. Crucially, add the result parameters here — each with a unit and reference range — so the result form knows what to ask for.",
          placement: 'left',
          tip: 'A test with no parameters falls back to a single free-text result box — fine for qualitative tests, but add parameters for anything with discrete values.' },
        { selector: '[data-tour="lab-catalog"]',
          title: 'Setup — manage the test directory',
          body: "Every test you offer is listed here with its parameter count, price, and barcode requirement. Doctors order from this list. Edit any test to adjust parameters or pricing, or deactivate ones you no longer run.",
          placement: 'top' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Radiology — Radiographer / Radiologist flow
       ────────────────────────────────────────────────────────────── */
    radiology: [
        { title: 'Radiology walk-through — request to signed report',
          body: "We'll run one imaging study end-to-end the way you'll do every patient: pick it off the queue, acknowledge when the patient arrives, write up findings, then sign and publish. Then the setup side — building your exam menu.",
          placement: 'center' },
        { selector: '[data-tour="radio-tabs"]',
          title: 'Step 1 — the two sides of Radiology',
          body: "\"Reading room\" is your day-to-day: processing imaging requests. \"Exam Catalog\" is the setup side: defining which exams you offer. Start in the Reading room.",
          placement: 'bottom' },
        { selector: '[data-tour="radio-queue"]',
          title: 'Step 2 — pick a study',
          body: "Every imaging request a doctor has ordered lands here. STAT studies are flagged red — do those first. Each card shows the exam type, patient, and status. Click one to open it.",
          placement: 'bottom' },
        { selector: '[data-tour="radio-acknowledge"]',
          title: 'Step 3 — acknowledge when the patient arrives',
          body: "While a request is \"Pending\" you'll see the clinical notes and any prep warnings. When the patient is in front of you and imaging begins, click \"Acknowledge & begin exam\" — the status flips to In Progress and the report form unlocks.",
          placement: 'top',
          tip: 'If the exam needs patient prep (fasting, contrast), a red banner reminds you to verify it before you start.' },
        { selector: '[data-tour="radio-report"]',
          title: 'Step 4 — write your report',
          body: "Fill in the detailed findings and your conclusion/impression. If the exam uses contrast, record what you gave. You can paste a PACS/DICOM image URL too. If the catalog has default templates, these boxes come pre-filled to save typing.",
          placement: 'top' },
        { selector: '[data-tour="radio-publish"]',
          title: 'Step 5 — sign & publish',
          body: "Click \"Sign & publish report\" to release it to the ordering doctor. Findings and conclusion are both required — no blank reports leave the room.",
          placement: 'top',
          tip: 'Use the Print button in the report header any time to hand the patient or doctor a paper copy.' },
        { selector: '[data-tour="radio-new-exam"]',
          title: 'Setup — add an exam to your menu',
          body: "Switch to the Exam Catalog tab and click \"New exam\". Set its name, modality (X-ray / CT / MRI / Ultrasound…), body part, base price, and whether it needs prep or contrast. You can also pre-write default findings/impression templates so reporting is faster.",
          placement: 'left' },
        { selector: '[data-tour="radio-catalog"]',
          title: 'Setup — manage the exam directory',
          body: "Every exam you offer is listed here with its price and flags. Doctors pick from this list when they order imaging. Edit any row, or deactivate exams you no longer run.",
          placement: 'top' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Pharmacy — Pharmacist's dispense + receipt flow
       ────────────────────────────────────────────────────────────── */
    pharmacy: [
        { title: 'Pharmacist walk-through — dispense, sell, reconcile',
          body: "We'll cover both halves of your day: fulfilling doctors' prescriptions, and selling over-the-counter at the till. Then how to reconcile everything at end of shift. By the end you'll know every screen.",
          placement: 'center' },
        { selector: '[data-tour="pharmacy-tabs"]',
          title: 'Step 1 — the three modes',
          body: "\"Rx Fulfillment\" handles prescriptions sent from doctors. \"OTC Point of Sale\" is the walk-in retail till. \"Transactions\" is your end-of-shift log. Start in Rx Fulfillment.",
          placement: 'bottom' },
        { selector: '[data-tour="pharmacy-dispense-queue"]',
          title: 'Step 2 — pick the next prescription',
          body: "Prescriptions from doctors land in this queue with the patient's name and any allergies highlighted in red. Click a card to open it and see exactly what was prescribed.",
          placement: 'bottom' },
        { selector: '[data-tour="pharmacy-rx-actions"]',
          title: 'Step 3 — dispense, return, or print',
          body: "Once the prescription's open: tick off each item as you pack it, then \"Dispense & close\" to take payment. \"Return to doctor\" bounces it back with a reason (dose ambiguity, interaction). \"Print Rx\" gives the patient a paper copy.",
          placement: 'top',
          tip: 'Dispensing opens a payment box — collect Cash or push an M-Pesa STK prompt, and the receipt prints automatically once it settles.' },
        { selector: '[data-tour="pharmacy-otc-search"]',
          title: 'Step 4 — over-the-counter sales',
          body: "Switch to OTC Point of Sale for walk-in retail. Search your live stock here — each card shows price, quantity, and batch. Click Add to drop an item into the sale on the right.",
          placement: 'right',
          tip: 'Out-of-stock items can\'t be added, and you can\'t exceed what\'s in a batch — the till protects your stock counts.' },
        { selector: '[data-tour="pharmacy-pay"]',
          title: 'Step 5 — take the money',
          body: "The sale total is here with three one-tap buttons: Cash, Card, and M-Pesa. M-Pesa asks for the phone number and pushes an STK prompt; the customer approves on their phone and the payment posts automatically — no counting cash, no slips to lose.",
          placement: 'left',
          tip: 'If an M-Pesa push isn\'t approved in time it expires and you can retry or switch to cash.' },
        { selector: '[data-tour="pharmacy-transactions"]',
          title: 'Step 6 — reconcile at end of shift',
          body: "The Transactions tab lists every dispense and sale for the period with method and status. Filter by date, method, or status, see what you charged vs collected, and reprint any receipt. This is what you hand to accounting.",
          placement: 'top' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Inventory — Pharmacy / Lab manager
       ────────────────────────────────────────────────────────────── */
    inventory: [
        { title: 'Inventory walk-through — receive, store, and move stock',
          body: "This is your central logistics hub. Stock lives in separate locations (Main Store, Pharmacy, Lab, Wards) and flows between them. We'll walk the whole supply chain: receive a delivery, read your stock, then move it where it's needed.",
          placement: 'center' },
        { selector: '[data-tour="inv-locations"]',
          title: 'Step 1 — pick the location you\'re working in',
          body: "Each tab is a separate stock pool. Whatever you click here sets the context for everything below — the valuation, the table, and where transfers and deliveries land. Most work starts in Main Store.",
          placement: 'bottom' },
        { selector: '[data-tour="inv-procurement"]',
          title: 'Step 2 — receive stock from a supplier',
          body: "Click \"External procurement\" when a delivery arrives. Pick the catalog item (or tick \"Add as new catalog item\" to create it on the spot), then enter the supplier, batch number, quantity, and expiry. It books the stock into the location you selected.",
          placement: 'left',
          tip: 'Every delivery is a batch with its own expiry — Pharmacy automatically dispenses the soonest-to-expire batch first (FEFO).' },
        { selector: '[data-tour="inv-transfer"]',
          title: 'Step 3 — move stock between locations',
          body: "Click \"Internal transfer\" to send stock from the current location to another — e.g. Main Store → Pharmacy. Pick the destination, the item batch, and the quantity. It deducts from one side and adds to the other, with an audit note.",
          placement: 'left' },
        { selector: '[data-tour="inv-kpis"]',
          title: 'Step 4 — watch the numbers that matter',
          body: "At a glance: the selected location's total stock valuation, how many items are below their re-order level (restock alerts), and how many batches expire within 90 days. These flag what to order and what to use up.",
          placement: 'bottom' },
        { selector: '[data-tour="inv-search"]',
          title: 'Step 5 — find a specific item',
          body: "Search by name or item code, and filter by category, to jump straight to what you're looking for in this location's stock.",
          placement: 'bottom' },
        { selector: '[data-tour="inv-table"]',
          title: 'Step 6 — read the stock list',
          body: "Every item in the selected location with its category, quantity on hand, and unit price. This is your live ground truth for what's actually on the shelf.",
          placement: 'top' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Wards — Nurse's admission-to-discharge flow
       ────────────────────────────────────────────────────────────── */
    wards: [
        { title: 'Ward nurse walk-through — admission to discharge',
          body: "We'll run an inpatient end-to-end: read the bed board, admit a patient, then open their chart to administer ward stock, log observations, and finally discharge. The Bed Board is your single source of truth.",
          placement: 'center' },
        { selector: '[data-tour="ward-kpis"]',
          title: 'Step 1 — check capacity at a glance',
          body: "Before anything else: your total occupancy %, how many beds are free, and how many are tied up in cleaning or maintenance. This is the number a bed manager asks you for.",
          placement: 'bottom' },
        { selector: '[data-tour="ward-admit"]',
          title: 'Step 2 — admit a patient',
          body: 'Click "Admit patient". Pick a registered patient, assign an available bed (grouped by ward), and type the primary diagnosis. The bed flips to blue and an admission record opens.',
          placement: 'left',
          tip: 'The system locks the bed while you admit, so two nurses can\'t put two patients in the same bed.' },
        { selector: '[data-tour="bed-board"]',
          title: 'Step 3 — read the bed board',
          body: "Every ward, every bed, colour-coded: white/green = free, blue = occupied (pulsing), purple = cleaning, amber = maintenance. Occupied beds show the patient, diagnosis, and admission date. Click an occupied bed to open that patient's inpatient chart.",
          placement: 'top' },
        { selector: '[data-tour="bed-board"]',
          title: 'Step 4 — inside the chart: administer ward stock',
          body: "Opening an occupied bed slides out the inpatient chart. In \"Administer ward inventory\" you pick stock from the ward, set a quantity, Add it to the cart, then \"Administer & log to audit trail\" — inventory decrements and the cost lands on the patient's bill.",
          placement: 'center' },
        { selector: '[data-tour="bed-board"]',
          title: 'Step 5 — inside the chart: log an observation',
          body: "Use the Clinical log in the same chart to append vitals, medication response, or anything the next shift should know, and \"Commit observation\" to write it to the audit trail. You can also print an admission slip from the footer.",
          placement: 'center' },
        { selector: '[data-tour="bed-board"]',
          title: 'Step 6 — discharge',
          body: "When the patient's ready to go, click \"Execute discharge protocol\" at the bottom of their chart. The admission closes and the bed flips to cleaning so housekeeping turns it before the next patient.",
          placement: 'center' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Appointments — Receptionist booking flow
       ────────────────────────────────────────────────────────────── */
    appointments: [
        { title: 'Appointments walk-through — book and run the clinic diary',
          body: "This is the clinic's diary. We'll go through exactly what you do every day: book a follow-up, narrow the list to the day you care about, then work each appointment as patients arrive — confirm, complete, no-show, or cancel.",
          placement: 'center' },
        { selector: '[data-tour="appt-new"]',
          title: 'Step 1 — book a new appointment',
          body: "Click \"New appointment\". A form opens: pick the patient, the doctor, the date and time, and an optional note (reason for visit). Slot availability is checked on the server, so two receptionists booking the same moment can't double-book.",
          placement: 'left',
          tip: 'If you already have a patient open elsewhere in the system, the form pre-selects them — open patient → New appointment → done.' },
        { selector: '[data-tour="appt-filters"]',
          title: 'Step 2 — narrow to the day you\'re working',
          body: "Filter by status (Scheduled / Confirmed / Completed / Cancelled / No-Show) and a From–To date range. It defaults to today onwards. Set \"From\" and \"To\" to the same day to see just that day's diary.",
          placement: 'bottom' },
        { selector: '[data-tour="appt-list"]',
          title: 'Step 3 — read the schedule',
          body: "Appointments are grouped by day, each card showing the time, patient, OP number, doctor, and status badge. This is your at-a-glance running order for the clinic.",
          placement: 'top' },
        { selector: '[data-tour="appt-actions"]',
          title: 'Step 4 — work each appointment as it happens',
          body: "On every active appointment card you get the buttons that move it along: \"Confirm\" when the patient calls ahead, \"Mark completed\" once they've been seen, \"No-show\" if they never arrive, and \"Cancel\" to call it off. Each click updates the status instantly.",
          placement: 'left',
          tip: 'Completed and Cancelled appointments lock — their action buttons disappear so you can\'t change a closed record.' },
        { selector: '[data-tour="appt-refresh"]',
          title: 'Step 5 — pull the latest',
          body: "Another receptionist booked from a different desk? Click Refresh to re-pull the diary so you're always looking at the current schedule.",
          placement: 'bottom' },
        { title: 'That\'s the whole diary',
          body: 'Book → filter to the day → confirm / complete / no-show as patients flow through. Click "?" in the top bar any time to replay this.',
          placement: 'center' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Billing — Cashier's flow
       ────────────────────────────────────────────────────────────── */
    billing: [
        { title: 'Cashier walk-through — invoice to receipt',
          body: "Find the patient, open their bill, take the money, settle. Cash, Card, or M-Pesa — we'll walk all three, then where to reconcile M-Pesa at end of shift.",
          placement: 'center' },
        { selector: '[data-tour="billing-queue"]',
          title: 'Step 1 — pick from the pending queue',
          body: "Every patient with an unpaid invoice is listed here, each card showing their name, OP number, and balance due. Click one to open their bill in the workspace.",
          placement: 'right' },
        { selector: '[data-tour="billing-search"]',
          title: 'Step 2 — search for a specific patient',
          body: "Got a long queue? Type a name or OP number here to filter straight to the invoice you need.",
          placement: 'bottom' },
        { selector: '[data-tour="billing-pay"]',
          title: 'Step 3 — review the bill and take payment',
          body: "Opening an invoice shows the itemized breakdown and balance due on the right. Pick a payment method — Cash, M-Pesa, or Card — then confirm. M-Pesa pushes an STK prompt to the patient's phone and settles automatically when they enter their PIN; Cash closes the bill immediately.",
          placement: 'left',
          tip: 'Use the Print button in the dark invoice header to hand the patient a printed invoice or receipt.' },
        { selector: '[data-tour="billing-mpesa"]',
          title: 'Step 4 — reconcile M-Pesa at close',
          body: "Click \"M-Pesa Ledger\" to see every STK push with its receipt number, payer phone, amount, and status. This is what you reconcile against your bank settlement statement at end of shift.",
          placement: 'bottom' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Cheque Register — Finance team, bidirectional flow
       ────────────────────────────────────────────────────────────── */
    cheques: [
        { title: 'Cheque register walk-through — both directions',
          body: "Cheques you RECEIVE (insurer paying you, employer paying for an employee's care) AND cheques you ISSUE (paying a supplier, refunding a patient) live in one ledger. Different lifecycles, same screen.",
          placement: 'center' },
        { selector: '[data-tour="cheque-direction-tabs"]',
          title: 'Step 1 — pick Incoming or Outgoing',
          body: "The whole page swaps based on direction — KPI tiles, status options, table columns, even the New-cheque form change to match.",
          placement: 'bottom' },
        { selector: '[data-tour="cheque-kpis"]',
          title: 'Step 2 — scan the status tiles',
          body: "Incoming: Received → In-transit → Cleared → Bounced. Outgoing: Issued → In-transit → Cleared → Returned. Each tile shows the count and the running total.",
          placement: 'bottom' },
        { selector: '[data-tour="cheque-search"]',
          title: 'Step 3 — find a specific cheque',
          body: "Search by cheque number, counterparty (drawer for incoming, payee for outgoing), or bank.",
          placement: 'bottom' },
        { selector: '[data-tour="cheque-new"]',
          title: 'Step 4 — record a new cheque',
          body: "Incoming asks who wrote it to you; outgoing asks who you wrote it to. Different forms, same button.",
          placement: 'left',
          tip: 'Link incoming cheques to an Invoice or Patient — that auto-applies the payment when the cheque clears.' },
        { selector: '[data-tour="cheque-row-actions"]',
          title: 'Step 5 — work the lifecycle',
          body: "Incoming: Deposit → Clear / Bounce. Outgoing: Dispatch → Clear / Return / Stop. Cancel any time before a terminal state. Each transition logs who, when, and (where required) why.",
          placement: 'left' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Messages — quick orientation
       ────────────────────────────────────────────────────────────── */
    messages: [
        { title: 'Messages walk-through — how staff talk in real time',
          body: "Everything here is live and audit-logged. We'll cover the lot: read your inbox, start a private chat, spin up a group huddle, hold the conversation, and send. No more shouting across the ward.",
          placement: 'center' },
        { selector: '[data-tour="msg-list"]',
          title: 'Step 1 — your conversations',
          body: "Every chat you're in, sorted by latest activity, each tagged Direct, Group, or Department. A red badge shows how many unread messages a thread has. Click one to open it.",
          placement: 'right' },
        { selector: '[data-tour="msg-new-direct"]',
          title: 'Step 2 — start a direct message',
          body: "Click the person icon to message one colleague privately. Search the staff directory by name or email, pick them, and you're talking — just the two of you, logged centrally.",
          placement: 'bottom' },
        { selector: '[data-tour="msg-new-group"]',
          title: 'Step 3 — start a group huddle',
          body: "Click the + to create a group for a case discussion or a shift handover. Give it a name and add as many staff as you need. Department channels (ICU, Pharmacy…) also show up in your list automatically.",
          placement: 'bottom' },
        { selector: '[data-tour="msg-thread"]',
          title: 'Step 4 — the conversation',
          body: "Once you open a chat, the full history loads here — your messages on the right, everyone else's on the left with their name. New messages arrive instantly, no refresh, because it's a live connection.",
          placement: 'left',
          tip: 'Opening a thread clears its unread badge automatically — the sender sees you\'ve caught up.' },
        { selector: '[data-tour="msg-thread"]',
          title: 'Step 5 — type and send',
          body: "Write in the box at the bottom of the conversation and hit Send (or Enter). The other people in the thread get it the moment you send — and a notification if they're not looking.",
          placement: 'top' },
    ],

    notifications: [
        { title: 'Notifications inbox',
          body: "Anything the system needs to surface — critical lab values, dispense backlog, expired consents — lands here with a deep link to the source.",
          placement: 'center' },
        { selector: '[data-tour="notif-list"]',
          title: 'Step 1 — read top-down',
          body: "Unread items have a coloured dot. Click to jump to whatever the notification is about; it marks read automatically.",
          placement: 'right' },
        { selector: '[data-tour="notif-read-all"]',
          title: 'Step 2 — bulk-clear unread state',
          body: "End of shift, hit Mark all read. Doesn't delete — the history is preserved.",
          placement: 'left' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Settings — Admin configuration tour
       ────────────────────────────────────────────────────────────── */
    settings: [
        { title: 'Settings walk-through',
          body: "Every per-tenant configuration lives here. We'll show you where to find the common ones and how to roll out a change.",
          placement: 'center' },
        { selector: '[data-tour="settings-categories"]',
          title: 'Step 1 — find the category',
          body: "Branding, working hours, billing, lab/radiology defaults, notifications, privacy. Tabs lazy-load so the page stays quick.",
          placement: 'bottom' },
        { selector: '[data-tour="settings-list"]',
          title: 'Step 2 — change the value',
          body: "Each setting picks the right widget for its type — text input, number spinner, toggle, JSON editor. Sensitive values mask until you click the eye.",
          placement: 'top' },
        { selector: '[data-tour="settings-custom"]',
          title: 'Step 3 — add a custom setting',
          body: "Hospital has a quirky requirement? Add a custom key with its data type and default. Becomes available to whichever module reads its category.",
          placement: 'top' },
        { selector: '[data-tour="settings-save"]',
          title: 'Step 4 — save in bulk',
          body: "Make all your changes, then save once. The button counts unsaved changes so you don't accidentally walk away with dirty state.",
          placement: 'left' },
        { selector: '[data-tour="restart-tours"]',
          title: 'Step 5 — replay all tours for new staff',
          body: 'Onboarding someone at a shared workstation? Reset every module\'s "tour-complete" flag here — next visit fires the walk-through fresh.',
          placement: 'left' },
    ],

    branding: [
        { title: 'Branding Studio — make the system look like your hospital',
          body: "Everything here changes how your workspace and printed documents look. We'll go top to bottom: logo, sign-in background, colours, print templates — then preview it and save. Nothing goes live until you hit Save.",
          placement: 'center' },
        { selector: '[data-tour="branding-logo"]',
          title: 'Step 1 — upload your logo',
          body: "Click the box to upload a square PNG, JPG, or SVG (transparent background recommended, under 600 KB). It appears in the sidebar, on the sign-in screen, and on every printed document. Hover the image to Replace or Remove it.",
          placement: 'top' },
        { selector: '[data-tour="branding-background"]',
          title: 'Step 2 — set your sign-in background',
          body: "This photo overlays the brand panel on the login screen. Pick something calm and low-contrast (under 900 KB) so the sign-in form stays readable. Leave it blank to use the default cyan/teal gradient.",
          placement: 'top' },
        { selector: '[data-tour="branding-colors"]',
          title: 'Step 3 — choose your brand colours',
          body: "Set a Primary and Accent colour with the picker or by typing a hex code. These tint buttons, links, and headers across the whole app. Leave blank to keep MediFleet's defaults.",
          placement: 'top',
          tip: 'Pick hues that pass a 4.5:1 contrast ratio against white so text stays legible — the defaults already do.' },
        { selector: '[data-tour="branding-templates"]',
          title: 'Step 4 — set up printed documents',
          body: "Header and footer text, a layout style (Modern / Classic / Minimal), and whether to print your logo. This is what lands on invoices, receipts, prescriptions, lab reports, and discharge summaries.",
          placement: 'top' },
        { selector: '[data-tour="branding-preview"]',
          title: 'Step 5 — preview before you commit',
          body: "This shows exactly how your branding lands on the sign-in screen — logo, colours, and background together — so you can fine-tune before anyone else sees it.",
          placement: 'top' },
        { selector: '[data-tour="branding-save"]',
          title: 'Step 6 — save to go live',
          body: "Nothing you changed is live until you click \"Save branding\". The button stays greyed out until you've made a change and lights up an \"Unsaved changes\" badge so you never walk away with a half-finished look.",
          placement: 'left' },
    ],

    accounting: [
        { title: 'Accounting walk-through — your full general ledger',
          body: "This is proper managerial accounting: chart of accounts, journals, statements, debtors, bank rec, currencies. Auto-posting already wires every cleared payment into the GL — we'll show you where everything lives.",
          placement: 'center' },
        { selector: '[data-tour="acc-tabs"]',
          title: 'Step 1 — the eight sections',
          body: "Across the top: Chart of Accounts, Journal Entries, Reports, Debtors, Bank, Configuration, Currencies & FX, and Settings. Click between them here. We'll start on Chart of Accounts.",
          placement: 'bottom' },
        { selector: '[data-tour="acc-coa"]',
          title: 'Step 2 — chart of accounts',
          body: "Your five-tier hierarchy (Assets / Liabilities / Equity / Revenue / Expenses). Set this up first — every other screen needs accounts to post into. \"New account\" adds one.",
          placement: 'top' },
        { selector: '[data-tour="acc-tabs"]',
          title: 'Step 3 — journal entries',
          body: "Open the Journal Entries tab for year-end adjustments, depreciation, and accruals. The server enforces debits = credits and stamps your user ID on every line. Post to commit, or reverse a posted entry.",
          placement: 'bottom' },
        { selector: '[data-tour="acc-tabs"]',
          title: 'Step 4 — reports',
          body: "The Reports tab computes your balance sheet, income statement, cash flow, and trial balance live off the GL, with date-range filters and CSV export.",
          placement: 'bottom' },
        { selector: '[data-tour="acc-tabs"]',
          title: 'Step 5 — debtors & insurance claims',
          body: "The Debtors tab tracks insurance claims through their lifecycle: submit, age, settle when paid, reject the rejected portion. Every transition auto-posts to accounts receivable.",
          placement: 'bottom' },
        { selector: '[data-tour="acc-tabs"]',
          title: 'Step 6 — bank, configuration & currencies',
          body: "Bank reconciles your statement against the books; Configuration sets the ledger mappings that auto-posting uses (e.g. which account \"invoice paid\" hits); Currencies & FX manages exchange rates. Set the mappings once and auto-posting handles the rest.",
          placement: 'bottom',
          tip: 'A missing ledger mapping silently strands entries — the Configuration tab flags them so you can fix it.' },
    ],

    payhero: [
        { title: 'M-Pesa Payments — collect at the till & pharmacy',
          body: "This is where you connect your hospital's own Safaricom shortcode so patients can pay by M-Pesa. Let me walk you through the whole setup — it takes about two minutes.",
          placement: 'center' },
        { selector: '[data-tour="mpesa-flow"]',
          title: 'First, understand where the money goes',
          body: "Every shilling a patient pays settles into YOUR hospital's own bank account, on your own schedule. MediFleet never holds or touches your money — it only triggers the M-Pesa prompt and shows you the result live.",
          placement: 'bottom',
          tip: "The only money MediFleet ever charges you is your monthly subscription — never a cut of patient payments." },
        { selector: '[data-tour="mpesa-shortcode"]',
          title: 'Step 1 — enter your Safaricom shortcode',
          body: "Type the PayBill or Buy-Goods Till your hospital already owns, and pick its type (PayBill needs an account number; a Till doesn't). This is the only number you need — there's nothing to copy from any payment provider.",
          placement: 'right' },
        { selector: '[data-tour="mpesa-settlement"]',
          title: 'Step 2 — choose your settlement bank',
          body: "Pick the bank and enter the account number + name where your M-Pesa proceeds should land. This is your hospital's account — the money settles straight to you.",
          placement: 'right' },
        { selector: '[data-tour="mpesa-editor"]',
          title: 'Step 3 — save',
          body: "Click Save settings. Your details are stored and sent to MediFleet, who finishes activating M-Pesa for your till on the platform side.",
          placement: 'top' },
        { selector: '[data-tour="mpesa-status"]',
          title: 'Step 4 — watch the status',
          body: "This card tells you whether M-Pesa is live yet. While it says 'awaiting activation', collection stays disabled. Once MediFleet activates your till it flips to live and you can take payments at the till and pharmacy.",
          placement: 'left' },
        { selector: '[data-tour="mpesa-test"]',
          title: 'Step 5 — send a KES 1 test',
          body: "Once you're live, enter your own phone number and send a real KES 1 prompt. Approve it on your phone to confirm the whole chain works end-to-end before you take a real patient payment.",
          placement: 'left',
          tip: "The test unlocks only after MediFleet activates your till — until then the button stays disabled." },
    ],

    /* ──────────────────────────────────────────────────────────────
       Superadmin — per-hospital Pay Hero provisioning (operator side)
       ────────────────────────────────────────────────────────────── */
    payhero_provisioning: [
        { title: 'M-Pesa Provisioning — wire a hospital',
          body: "This is the operator side: here you connect each hospital's Pay Hero account so they can collect M-Pesa. Hospitals never see this screen — they only see whether their M-Pesa is live.",
          placement: 'center' },
        { selector: '[data-tour="prov-guide"]',
          title: 'The model — you never touch hospital money',
          body: "Each hospital owns its OWN Pay Hero account. Patient money flows into the hospital's account and settles to the hospital's bank. You only trigger the push and relay status. The only money you collect is subscriptions, on the separate Subscription Billing screen.",
          placement: 'bottom' },
        { selector: '[data-tour="prov-hospital"]',
          title: 'Step 1 — pick the hospital',
          body: "Choose which hospital you're wiring. Its saved config (if any) loads below.",
          placement: 'bottom' },
        { selector: '[data-tour="prov-payhero"]',
          title: 'Step 2 — paste their Pay Hero wiring',
          body: "From the hospital's own Pay Hero account, paste the Channel ID, API username/password, and webhook signing secret. Saving a channel id is what flips their M-Pesa to live.",
          placement: 'right',
          tip: "Each hospital signs its callbacks with its own webhook secret — leave it blank only if they share the platform default account." },
        { selector: '[data-tour="prov-test"]',
          title: 'Step 3 — send a KES 1 test',
          body: "After saving, send a real KES 1 STK push using the hospital's wiring to confirm money actually moves and the callback settles. The result shows here.",
          placement: 'left' },
    ],

    /* ──────────────────────────────────────────────────────────────
       Superadmin — Subscription Billing (the operator's OWN money)
       ────────────────────────────────────────────────────────────── */
    platform_subscriptions: [
        { title: 'Subscription Billing — the one rail where you get paid',
          body: "Hospitals' patient payments never touch you. This screen is the only place MediFleet receives money: you charge each tenant their subscription into your OWN Pay Hero account. Let me show you how to set it up and collect.",
          placement: 'center' },
        { selector: '[data-tour="sub-guide"]',
          title: 'How it works',
          body: "You configure MediFleet's own Pay Hero account once. Then, each cycle, you charge a tenant's billing phone by M-Pesa — the money lands in your account and settles to your bank. Watch it complete live below.",
          placement: 'bottom' },
        { selector: '[data-tour="sub-health"]',
          title: 'Readiness check',
          body: "This banner tells you whether your billing account is ready. If anything's missing — channel id, credentials, webhook secret, settlement bank, or PUBLIC_BASE_URL — it lists exactly what to fix. Charging stays locked until it's green.",
          placement: 'bottom' },
        { selector: '[data-tour="sub-config"]',
          title: 'Step 1 — provision your account',
          body: "Paste MediFleet's OWN Pay Hero channel id, API username/password, and webhook secret, then pick the settlement bank where YOU get paid. Save. Leave the password/secret blank to keep what's already stored.",
          placement: 'right',
          tip: "These are your account's values — completely separate from the hospital accounts you wire on the M-Pesa Provisioning screen." },
        { selector: '[data-tour="sub-charge"]',
          title: 'Step 2 — charge a tenant',
          body: "Pick a tenant, set their billing phone (you can save it as their default), enter the amount + a period label, and Charge. Use the Test button first to send a real KES 1 push and confirm the chain works.",
          placement: 'left' },
        { selector: '[data-tour="sub-activity"]',
          title: 'Step 3 — watch it settle live',
          body: "Every charge appears here and flips from Pending → Success the instant the tenant approves and the callback settles — no refresh needed. The M-Pesa receipt number is your proof of payment.",
          placement: 'top' },
    ],

    support: [
        { title: 'MediFleet Support — get help, end to end',
          body: "This is your direct line to the MediFleet platform team. We'll walk the whole loop: raise a ticket, find it again, hold the conversation, and close it when you're sorted.",
          placement: 'center' },
        { selector: '[data-tour="support-new"]',
          title: 'Step 1 — raise a ticket',
          body: "Click \"New ticket\". Give it a subject, pick a category (Billing, Bug, Feature, Account, Onboarding, Other) and a priority, then describe what's going on — include steps, what you expected, and any error messages.",
          placement: 'left',
          tip: 'Set priority to Urgent only for something blocking the hospital — it jumps the platform team\'s queue.' },
        { selector: '[data-tour="support-filters"]',
          title: 'Step 2 — filter the inbox',
          body: "These chips filter your whole ticket history by status — All, Open, In Progress, Waiting on Customer, Resolved, Closed — and each shows a live count. Use them to find the ticket you care about fast.",
          placement: 'bottom' },
        { selector: '[data-tour="support-list"]',
          title: 'Step 3 — pick a ticket',
          body: "Every ticket you've raised, newest activity first, with its status dot, number, category, and when it last moved. Click one to open the conversation.",
          placement: 'right' },
        { selector: '[data-tour="support-thread"]',
          title: 'Step 4 — read the conversation',
          body: "The full back-and-forth opens here. MediFleet's replies are tagged with a shield on the left; your messages sit on the right. The header shows the ticket's category, priority, and current status.",
          placement: 'left' },
        { selector: '[data-tour="support-reply"]',
          title: 'Step 5 — reply',
          body: "Type into this box and hit send to add to the thread. The MediFleet team is notified and the ticket flips to \"In Progress\" so you both know it's live.",
          placement: 'top' },
        { selector: '[data-tour="support-close"]',
          title: 'Step 6 — close it out',
          body: "Once your issue is resolved, click \"Mark as closed\". It stops the back-and-forth but keeps the full history — you can always reopen by raising a new ticket that references it.",
          placement: 'right' },
    ],

    privacy: [
        { title: 'Privacy & KDPA',
          body: "Section 26 access logs (who saw what), Section 30 consent records (what they allowed), Section 40 erasure requests, Section 43 breach notification with a 72-hour countdown.",
          placement: 'center' },
    ],

    referrals: [
        { title: 'Referrals',
          body: "Out-bound referrals to specialists with status tracking; inbound queue for receiving facilities.",
          placement: 'center' },
    ],

    analytics: [
        { title: 'Analytics',
          body: "Aggregated dashboards across encounters, pharmacy turnover, lab throughput, billing performance, per-doctor productivity. Filter by date-range to slice the period you care about.",
          placement: 'center' },
    ],
};

/* ── Per-user progress (localStorage) ────────────────────────────── */

export function journeyStorageKey(userId) {
    return `hms_journey_progress_${userId || 'anon'}`;
}

export function readProgress(userId) {
    try {
        const raw = localStorage.getItem(journeyStorageKey(userId));
        if (!raw) return new Set();
        const parsed = JSON.parse(raw);
        return new Set(Array.isArray(parsed) ? parsed : []);
    } catch {
        return new Set();
    }
}

export function writeProgress(userId, set) {
    try {
        localStorage.setItem(journeyStorageKey(userId), JSON.stringify([...set]));
    } catch { /* private mode / quota — silently degrade */ }
}
