"""Expanded patient demographics and clinical baselines

Revision ID: 01559f036ec7
Revises: f0fafd4890d7
Create Date: 2026-04-14 16:35:40.091729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01559f036ec7'
down_revision: Union[str, Sequence[str], None] = 'f0fafd4890d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('marital_status', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('religion', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('primary_language', sa.String(length=100), nullable=True))
    op.add_column('patients', sa.Column('allergies', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('chronic_conditions', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('employer_name', sa.String(length=255), nullable=True))
    op.alter_column('patients', 'notes',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('patients', 'employer_name')
    op.drop_column('patients', 'chronic_conditions')
    op.drop_column('patients', 'allergies')
    op.drop_column('patients', 'primary_language')
    op.drop_column('patients', 'religion')
    op.drop_column('patients', 'marital_status')
    # ### end Alembic commands ###
