"""Add M-Pesa Models

Revision ID: 9302d7caa6cd
Revises: bab9bbb377e4
Create Date: 2026-05-05 18:09:39.981274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9302d7caa6cd'
down_revision: Union[str, Sequence[str], None] = 'bab9bbb377e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpesa_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paybill_number', sa.String(length=20), nullable=False),
    sa.Column('consumer_key_encrypted', sa.String(length=255), nullable=False),
    sa.Column('consumer_secret_encrypted', sa.String(length=255), nullable=False),
    sa.Column('passkey_encrypted', sa.String(length=255), nullable=False),
    sa.Column('account_reference', sa.String(length=50), nullable=True),
    sa.Column('transaction_desc', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('kcb_account_number', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mpesa_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('merchant_request_id', sa.String(length=100), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('result_desc', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpesa_transactions_checkout_request_id'), 'mpesa_transactions', ['checkout_request_id'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_invoice_id'), 'mpesa_transactions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_merchant_request_id'), 'mpesa_transactions', ['merchant_request_id'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_phone_number'), 'mpesa_transactions', ['phone_number'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_receipt_number'), 'mpesa_transactions', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_mpesa_transactions_status'), 'mpesa_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_transaction_date'), 'mpesa_transactions', ['transaction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mpesa_transactions_transaction_date'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_status'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_receipt_number'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_phone_number'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_merchant_request_id'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_invoice_id'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_checkout_request_id'), table_name='mpesa_transactions')
    op.drop_table('mpesa_transactions')
    op.drop_table('mpesa_configs')
    # ### end Alembic commands ###
