"""add_radiology_tables

Revision ID: 9ce4ed8c39f3
Revises: 9302d7caa6cd
Create Date: 2026-05-06 12:15:26.189294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ce4ed8c39f3'
down_revision: Union[str, Sequence[str], None] = '9302d7caa6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpesa_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paybill_number', sa.String(length=20), nullable=False),
    sa.Column('consumer_key_encrypted', sa.String(length=255), nullable=False),
    sa.Column('consumer_secret_encrypted', sa.String(length=255), nullable=False),
    sa.Column('passkey_encrypted', sa.String(length=255), nullable=False),
    sa.Column('account_reference', sa.String(length=50), nullable=True),
    sa.Column('transaction_desc', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('kcb_account_number', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mpesa_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('merchant_request_id', sa.String(length=100), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=True),
    sa.Column('receipt_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('result_desc', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpesa_transactions_checkout_request_id'), 'mpesa_transactions', ['checkout_request_id'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_invoice_id'), 'mpesa_transactions', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_merchant_request_id'), 'mpesa_transactions', ['merchant_request_id'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_phone_number'), 'mpesa_transactions', ['phone_number'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_receipt_number'), 'mpesa_transactions', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_mpesa_transactions_status'), 'mpesa_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_mpesa_transactions_transaction_date'), 'mpesa_transactions', ['transaction_date'], unique=False)
    op.drop_table('tenants')
    op.drop_table('superadmins')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('superadmins',
    sa.Column('admin_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('admin_id', name=op.f('superadmins_pkey')),
    sa.UniqueConstraint('email', name=op.f('superadmins_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('tenants',
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('db_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('theme_color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('tenants_pkey')),
    sa.UniqueConstraint('db_name', name=op.f('tenants_db_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('domain', name=op.f('tenants_domain_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_mpesa_transactions_transaction_date'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_status'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_receipt_number'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_phone_number'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_merchant_request_id'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_invoice_id'), table_name='mpesa_transactions')
    op.drop_index(op.f('ix_mpesa_transactions_checkout_request_id'), table_name='mpesa_transactions')
    op.drop_table('mpesa_transactions')
    op.drop_table('mpesa_configs')
    # ### end Alembic commands ###
