"""Add Medical History, Consent, and Data Access Log tables

Revision ID: bab9bbb377e4
Revises: ea2c5028a38c
Create Date: 2026-04-30 10:23:49.176898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab9bbb377e4'
down_revision: Union[str, Sequence[str], None] = 'ea2c5028a38c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
