"""Add Wards and Beds tables

Revision ID: ea2c5028a38c
Revises: b7e34e24c767
Create Date: 2026-04-23 10:12:14.628329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea2c5028a38c'
down_revision: Union[str, Sequence[str], None] = 'b7e34e24c767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wards',
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ward_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stock_transfers',
    sa.Column('transfer_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=False),
    sa.Column('to_location_id', sa.Integer(), nullable=False),
    sa.Column('quantity_transferred', sa.Integer(), nullable=False),
    sa.Column('transferred_by', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.batch_id'], ),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.item_id'], ),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.location_id'], ),
    sa.ForeignKeyConstraint(['transferred_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    op.create_index(op.f('ix_stock_transfers_item_id'), 'stock_transfers', ['item_id'], unique=False)
    op.create_table('admission_records',
    sa.Column('admission_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('admitting_doctor_id', sa.Integer(), nullable=False),
    sa.Column('primary_diagnosis', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('admitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discharge_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['admitting_doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['bed_id'], ['beds.bed_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('admission_id')
    )
    op.create_index(op.f('ix_admission_records_admitted_at'), 'admission_records', ['admitted_at'], unique=False)
    op.create_index(op.f('ix_admission_records_bed_id'), 'admission_records', ['bed_id'], unique=False)
    op.create_index(op.f('ix_admission_records_patient_id'), 'admission_records', ['patient_id'], unique=False)
    op.create_index(op.f('ix_admission_records_status'), 'admission_records', ['status'], unique=False)
    op.drop_index(op.f('ix_drug_inventory_brand_name'), table_name='drug_inventory')
    op.drop_index(op.f('ix_drug_inventory_category'), table_name='drug_inventory')
    op.drop_index(op.f('ix_drug_inventory_generic_name'), table_name='drug_inventory')
    op.execute('DROP TABLE drug_inventory CASCADE')
    op.add_column('beds', sa.Column('ward_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('beds_patient_id_key'), 'beds', type_='unique')
    op.drop_index(op.f('ix_beds_ward_name'), table_name='beds')
    op.drop_constraint(op.f('beds_patient_id_fkey'), 'beds', type_='foreignkey')
    op.create_foreign_key(None, 'beds', 'wards', ['ward_id'], ['ward_id'])
    op.drop_column('beds', 'patient_id')
    op.drop_column('beds', 'discharged_at')
    op.drop_column('beds', 'ward_name')
    op.drop_column('beds', 'admitted_at')
    op.add_column('dispense_logs', sa.Column('item_id', sa.Integer(), nullable=False))
    op.add_column('dispense_logs', sa.Column('batch_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_dispense_logs_drug_id'), table_name='dispense_logs')
    op.create_index(op.f('ix_dispense_logs_item_id'), 'dispense_logs', ['item_id'], unique=False)
    #op.drop_constraint(op.f('dispense_logs_drug_id_fkey'), 'dispense_logs', type_='foreignkey')
    op.create_foreign_key(None, 'dispense_logs', 'inventory_items', ['item_id'], ['item_id'])
    op.create_foreign_key(None, 'dispense_logs', 'stock_batches', ['batch_id'], ['batch_id'])
    op.drop_column('dispense_logs', 'drug_id')
    op.add_column('inventory_items', sa.Column('generic_name', sa.String(length=255), nullable=True))
    op.add_column('inventory_items', sa.Column('dosage_form', sa.String(length=50), nullable=True))
    op.add_column('inventory_items', sa.Column('strength', sa.String(length=50), nullable=True))
    op.add_column('inventory_items', sa.Column('requires_prescription', sa.Boolean(), nullable=True))
    op.add_column('inventory_items', sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False))
    op.create_index(op.f('ix_inventory_items_generic_name'), 'inventory_items', ['generic_name'], unique=False)
    op.add_column('inventory_usage_logs', sa.Column('batch_id', sa.Integer(), nullable=False))
    op.add_column('inventory_usage_logs', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'inventory_usage_logs', 'stock_batches', ['batch_id'], ['batch_id'])
    op.create_foreign_key(None, 'inventory_usage_logs', 'locations', ['location_id'], ['location_id'])
    op.drop_column('inventory_usage_logs', 'item_name')
    op.drop_column('inventory_usage_logs', 'department')
    op.add_column('lab_test_catalog', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('lab_test_catalog', sa.Column('default_specimen_type', sa.String(length=100), nullable=False))
    op.drop_column('lab_test_catalog', 'department')
    op.add_column('lab_tests', sa.Column('record_id', sa.Integer(), nullable=True))
    op.add_column('lab_tests', sa.Column('clinical_notes', sa.String(), nullable=True))
    op.add_column('lab_tests', sa.Column('specimen_id', sa.String(length=100), nullable=True))
    op.add_column('lab_tests', sa.Column('specimen_type', sa.String(length=100), nullable=True))
    op.add_column('lab_tests', sa.Column('lab_technician_notes', sa.String(), nullable=True))
    op.add_column('lab_tests', sa.Column('sample_collected_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_lab_tests_record_id'), 'lab_tests', ['record_id'], unique=False)
    op.create_index(op.f('ix_lab_tests_specimen_id'), 'lab_tests', ['specimen_id'], unique=True)
    op.create_foreign_key(None, 'lab_tests', 'medical_records', ['record_id'], ['record_id'])
    op.add_column('medical_records', sa.Column('record_status', sa.String(length=50), nullable=True))
    op.add_column('medical_records', sa.Column('blood_pressure', sa.String(length=20), nullable=True))
    op.add_column('medical_records', sa.Column('respiratory_rate', sa.Integer(), nullable=True))
    op.add_column('medical_records', sa.Column('calculated_bmi', sa.Float(), nullable=True))
    op.add_column('medical_records', sa.Column('review_of_systems', sa.JSON(), nullable=True))
    op.add_column('medical_records', sa.Column('physical_examination', sa.String(), nullable=True))
    op.add_column('medical_records', sa.Column('internal_notes', sa.String(), nullable=True))
    op.add_column('medical_records', sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('medical_records', 'icd10_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_medical_records_record_status'), 'medical_records', ['record_status'], unique=False)
    op.drop_column('medical_records', 'diastolic_bp')
    op.drop_column('medical_records', 'systolic_bp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('systolic_bp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('medical_records', sa.Column('diastolic_bp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_medical_records_record_status'), table_name='medical_records')
    op.alter_column('medical_records', 'icd10_code',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('medical_records', 'follow_up_date')
    op.drop_column('medical_records', 'internal_notes')
    op.drop_column('medical_records', 'physical_examination')
    op.drop_column('medical_records', 'review_of_systems')
    op.drop_column('medical_records', 'calculated_bmi')
    op.drop_column('medical_records', 'respiratory_rate')
    op.drop_column('medical_records', 'blood_pressure')
    op.drop_column('medical_records', 'record_status')
    op.drop_constraint(None, 'lab_tests', type_='foreignkey')
    op.drop_index(op.f('ix_lab_tests_specimen_id'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_record_id'), table_name='lab_tests')
    op.drop_column('lab_tests', 'sample_collected_at')
    op.drop_column('lab_tests', 'lab_technician_notes')
    op.drop_column('lab_tests', 'specimen_type')
    op.drop_column('lab_tests', 'specimen_id')
    op.drop_column('lab_tests', 'clinical_notes')
    op.drop_column('lab_tests', 'record_id')
    op.add_column('lab_test_catalog', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('lab_test_catalog', 'default_specimen_type')
    op.drop_column('lab_test_catalog', 'category')
    op.add_column('inventory_usage_logs', sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('inventory_usage_logs', sa.Column('item_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inventory_usage_logs', type_='foreignkey')
    op.drop_constraint(None, 'inventory_usage_logs', type_='foreignkey')
    op.drop_column('inventory_usage_logs', 'location_id')
    op.drop_column('inventory_usage_logs', 'batch_id')
    op.drop_index(op.f('ix_inventory_items_generic_name'), table_name='inventory_items')
    op.drop_column('inventory_items', 'unit_cost')
    op.drop_column('inventory_items', 'requires_prescription')
    op.drop_column('inventory_items', 'strength')
    op.drop_column('inventory_items', 'dosage_form')
    op.drop_column('inventory_items', 'generic_name')
    op.add_column('dispense_logs', sa.Column('drug_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'dispense_logs', type_='foreignkey')
    op.drop_constraint(None, 'dispense_logs', type_='foreignkey')
    op.create_foreign_key(op.f('dispense_logs_drug_id_fkey'), 'dispense_logs', 'drug_inventory', ['drug_id'], ['drug_id'])
    op.drop_index(op.f('ix_dispense_logs_item_id'), table_name='dispense_logs')
    op.create_index(op.f('ix_dispense_logs_drug_id'), 'dispense_logs', ['drug_id'], unique=False)
    op.drop_column('dispense_logs', 'batch_id')
    op.drop_column('dispense_logs', 'item_id')
    op.add_column('beds', sa.Column('admitted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('beds', sa.Column('ward_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('beds', sa.Column('discharged_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('beds', sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'beds', type_='foreignkey')
    op.create_foreign_key(op.f('beds_patient_id_fkey'), 'beds', 'patients', ['patient_id'], ['patient_id'])
    op.create_index(op.f('ix_beds_ward_name'), 'beds', ['ward_name'], unique=False)
    op.create_unique_constraint(op.f('beds_patient_id_key'), 'beds', ['patient_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('beds', 'ward_id')
    op.create_table('drug_inventory',
    sa.Column('drug_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('generic_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('dosage_form', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('strength', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reorder_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requires_prescription', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_restocked', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('drug_id', name=op.f('drug_inventory_pkey'))
    )
    op.create_index(op.f('ix_drug_inventory_generic_name'), 'drug_inventory', ['generic_name'], unique=False)
    op.create_index(op.f('ix_drug_inventory_category'), 'drug_inventory', ['category'], unique=False)
    op.create_index(op.f('ix_drug_inventory_brand_name'), 'drug_inventory', ['brand_name'], unique=False)
    op.drop_index(op.f('ix_admission_records_status'), table_name='admission_records')
    op.drop_index(op.f('ix_admission_records_patient_id'), table_name='admission_records')
    op.drop_index(op.f('ix_admission_records_bed_id'), table_name='admission_records')
    op.drop_index(op.f('ix_admission_records_admitted_at'), table_name='admission_records')
    op.drop_table('admission_records')
    op.drop_index(op.f('ix_stock_transfers_item_id'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_table('wards')
    # ### end Alembic commands ###
