"""Initial schema

Revision ID: f0fafd4890d7
Revises: 
Create Date: 2026-04-14 16:17:24.318725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0fafd4890d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drug_inventory',
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('dosage_form', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('requires_prescription', sa.Boolean(), nullable=True),
    sa.Column('last_restocked', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('drug_id')
    )
    op.create_index(op.f('ix_drug_inventory_brand_name'), 'drug_inventory', ['brand_name'], unique=False)
    op.create_index(op.f('ix_drug_inventory_category'), 'drug_inventory', ['category'], unique=False)
    op.create_index(op.f('ix_drug_inventory_generic_name'), 'drug_inventory', ['generic_name'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=36), nullable=False),
    sa.Column('response_body', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('inventory_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reorder_threshold', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_inventory_items_category'), 'inventory_items', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_items_item_code'), 'inventory_items', ['item_code'], unique=True)
    op.create_index(op.f('ix_inventory_items_name'), 'inventory_items', ['name'], unique=False)
    op.create_table('lab_test_catalog',
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('turnaround_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('catalog_id')
    )
    op.create_index(op.f('ix_lab_test_catalog_test_name'), 'lab_test_catalog', ['test_name'], unique=True)
    op.create_table('locations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('codename', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_index(op.f('ix_permissions_codename'), 'permissions', ['codename'], unique=True)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('lab_test_required_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=True),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity_required', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['lab_test_catalog.catalog_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_test_required_items_catalog_id'), 'lab_test_required_items', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_lab_test_required_items_inventory_item_id'), 'lab_test_required_items', ['inventory_item_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('stock_batches',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.item_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_stock_batches_batch_number'), 'stock_batches', ['batch_number'], unique=False)
    op.create_index(op.f('ix_stock_batches_expiry_date'), 'stock_batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_stock_batches_item_id'), 'stock_batches', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_batches_location_id'), 'stock_batches', ['location_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_license_number'), 'users', ['license_number'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('inventory_usage_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity_used', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('used_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.item_id'], ),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_inventory_usage_logs_item_id'), 'inventory_usage_logs', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_usage_logs_timestamp'), 'inventory_usage_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_inventory_usage_logs_used_by_user_id'), 'inventory_usage_logs', ['used_by_user_id'], unique=False)
    op.create_table('patients',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('outpatient_no', sa.String(length=50), nullable=False),
    sa.Column('inpatient_no', sa.String(length=50), nullable=True),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('other_names', sa.String(length=150), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('id_type', sa.String(length=50), nullable=True),
    sa.Column('id_number', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('telephone_1', sa.String(length=20), nullable=True),
    sa.Column('telephone_2', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('postal_address', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=50), nullable=True),
    sa.Column('residence', sa.String(length=255), nullable=True),
    sa.Column('town', sa.String(length=100), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('nok_name', sa.String(length=255), nullable=True),
    sa.Column('nok_relationship', sa.String(length=100), nullable=True),
    sa.Column('nok_contact', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('registered_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('registered_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registered_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index('idx_patient_name', 'patients', ['surname', 'other_names'], unique=False)
    op.create_index(op.f('ix_patients_id_number'), 'patients', ['id_number'], unique=False)
    op.create_index(op.f('ix_patients_inpatient_no'), 'patients', ['inpatient_no'], unique=True)
    op.create_index(op.f('ix_patients_outpatient_no'), 'patients', ['outpatient_no'], unique=True)
    op.create_index(op.f('ix_patients_registered_by'), 'patients', ['registered_by'], unique=False)
    op.create_index(op.f('ix_patients_registered_on'), 'patients', ['registered_on'], unique=False)
    op.create_index(op.f('ix_patients_telephone_1'), 'patients', ['telephone_1'], unique=False)
    op.create_table('appointments',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('beds',
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('ward_name', sa.String(length=100), nullable=False),
    sa.Column('bed_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('admitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discharged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('bed_id'),
    sa.UniqueConstraint('bed_number'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_index(op.f('ix_beds_status'), 'beds', ['status'], unique=False)
    op.create_index(op.f('ix_beds_ward_name'), 'beds', ['ward_name'], unique=False)
    op.create_table('lab_tests',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('ordered_by', sa.Integer(), nullable=False),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('result_summary', sa.String(), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('billed_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catalog_id'], ['lab_test_catalog.catalog_id'], ),
    sa.ForeignKeyConstraint(['ordered_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_index(op.f('ix_lab_tests_catalog_id'), 'lab_tests', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_lab_tests_ordered_by'), 'lab_tests', ['ordered_by'], unique=False)
    op.create_index(op.f('ix_lab_tests_patient_id'), 'lab_tests', ['patient_id'], unique=False)
    op.create_index(op.f('ix_lab_tests_performed_by_id'), 'lab_tests', ['performed_by_id'], unique=False)
    op.create_index(op.f('ix_lab_tests_requested_at'), 'lab_tests', ['requested_at'], unique=False)
    op.create_index(op.f('ix_lab_tests_status'), 'lab_tests', ['status'], unique=False)
    op.create_table('medical_records',
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('spo2', sa.Integer(), nullable=True),
    sa.Column('chief_complaint', sa.String(), nullable=True),
    sa.Column('history_of_present_illness', sa.String(), nullable=True),
    sa.Column('icd10_code', sa.String(length=50), nullable=True),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('treatment_plan', sa.String(), nullable=True),
    sa.Column('prescription_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index(op.f('ix_medical_records_created_at'), 'medical_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_medical_records_doctor_id'), 'medical_records', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_medical_records_icd10_code'), 'medical_records', ['icd10_code'], unique=False)
    op.create_index(op.f('ix_medical_records_patient_id'), 'medical_records', ['patient_id'], unique=False)
    op.create_table('patient_queue',
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('acuity_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('queue_id')
    )
    op.create_index('idx_queue_dept_status', 'patient_queue', ['department', 'status'], unique=False)
    op.create_index(op.f('ix_patient_queue_assigned_to'), 'patient_queue', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_patient_queue_joined_at'), 'patient_queue', ['joined_at'], unique=False)
    op.create_index(op.f('ix_patient_queue_patient_id'), 'patient_queue', ['patient_id'], unique=False)
    op.create_table('dispense_logs',
    sa.Column('dispense_id', sa.Integer(), nullable=False),
    sa.Column('drug_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('quantity_dispensed', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dispensed_by', sa.Integer(), nullable=False),
    sa.Column('dispensed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dispensed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['drug_id'], ['drug_inventory.drug_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.record_id'], ),
    sa.PrimaryKeyConstraint('dispense_id')
    )
    op.create_index(op.f('ix_dispense_logs_dispensed_at'), 'dispense_logs', ['dispensed_at'], unique=False)
    op.create_index(op.f('ix_dispense_logs_dispensed_by'), 'dispense_logs', ['dispensed_by'], unique=False)
    op.create_index(op.f('ix_dispense_logs_drug_id'), 'dispense_logs', ['drug_id'], unique=False)
    op.create_index(op.f('ix_dispense_logs_patient_id'), 'dispense_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_dispense_logs_record_id'), 'dispense_logs', ['record_id'], unique=False)
    op.create_table('invoices',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('billing_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index('idx_invoice_status_date', 'invoices', ['status', 'billing_date'], unique=False)
    op.create_index(op.f('ix_invoices_appointment_id'), 'invoices', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_invoices_billing_date'), 'invoices', ['billing_date'], unique=False)
    op.create_index(op.f('ix_invoices_created_by'), 'invoices', ['created_by'], unique=False)
    op.create_index(op.f('ix_invoices_patient_id'), 'invoices', ['patient_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.invoice_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_invoice_id'), 'payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_transaction_reference'), 'payments', ['transaction_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_transaction_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_invoice_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_patient_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_by'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_billing_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_appointment_id'), table_name='invoices')
    op.drop_index('idx_invoice_status_date', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_dispense_logs_record_id'), table_name='dispense_logs')
    op.drop_index(op.f('ix_dispense_logs_patient_id'), table_name='dispense_logs')
    op.drop_index(op.f('ix_dispense_logs_drug_id'), table_name='dispense_logs')
    op.drop_index(op.f('ix_dispense_logs_dispensed_by'), table_name='dispense_logs')
    op.drop_index(op.f('ix_dispense_logs_dispensed_at'), table_name='dispense_logs')
    op.drop_table('dispense_logs')
    op.drop_index(op.f('ix_patient_queue_patient_id'), table_name='patient_queue')
    op.drop_index(op.f('ix_patient_queue_joined_at'), table_name='patient_queue')
    op.drop_index(op.f('ix_patient_queue_assigned_to'), table_name='patient_queue')
    op.drop_index('idx_queue_dept_status', table_name='patient_queue')
    op.drop_table('patient_queue')
    op.drop_index(op.f('ix_medical_records_patient_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_icd10_code'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_doctor_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_created_at'), table_name='medical_records')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_lab_tests_status'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_requested_at'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_performed_by_id'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_patient_id'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_ordered_by'), table_name='lab_tests')
    op.drop_index(op.f('ix_lab_tests_catalog_id'), table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_index(op.f('ix_beds_ward_name'), table_name='beds')
    op.drop_index(op.f('ix_beds_status'), table_name='beds')
    op.drop_table('beds')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_patients_telephone_1'), table_name='patients')
    op.drop_index(op.f('ix_patients_registered_on'), table_name='patients')
    op.drop_index(op.f('ix_patients_registered_by'), table_name='patients')
    op.drop_index(op.f('ix_patients_outpatient_no'), table_name='patients')
    op.drop_index(op.f('ix_patients_inpatient_no'), table_name='patients')
    op.drop_index(op.f('ix_patients_id_number'), table_name='patients')
    op.drop_index('idx_patient_name', table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_inventory_usage_logs_used_by_user_id'), table_name='inventory_usage_logs')
    op.drop_index(op.f('ix_inventory_usage_logs_timestamp'), table_name='inventory_usage_logs')
    op.drop_index(op.f('ix_inventory_usage_logs_item_id'), table_name='inventory_usage_logs')
    op.drop_table('inventory_usage_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_license_number'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stock_batches_location_id'), table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_item_id'), table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_expiry_date'), table_name='stock_batches')
    op.drop_index(op.f('ix_stock_batches_batch_number'), table_name='stock_batches')
    op.drop_table('stock_batches')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_lab_test_required_items_inventory_item_id'), table_name='lab_test_required_items')
    op.drop_index(op.f('ix_lab_test_required_items_catalog_id'), table_name='lab_test_required_items')
    op.drop_table('lab_test_required_items')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_codename'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('locations')
    op.drop_index(op.f('ix_lab_test_catalog_test_name'), table_name='lab_test_catalog')
    op.drop_table('lab_test_catalog')
    op.drop_index(op.f('ix_inventory_items_name'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_item_code'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_category'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_table('idempotency_keys')
    op.drop_index(op.f('ix_drug_inventory_generic_name'), table_name='drug_inventory')
    op.drop_index(op.f('ix_drug_inventory_category'), table_name='drug_inventory')
    op.drop_index(op.f('ix_drug_inventory_brand_name'), table_name='drug_inventory')
    op.drop_table('drug_inventory')
    # ### end Alembic commands ###
